# Generated by Django 6.0.4 on 2026-04-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-academic_start_year', 'code'], 'verbose_name_plural': 'Batches'},
        ),
    ]
