# Generated by Django 6.0.4 on 2026-04-15 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_batch_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='department',
        ),
    ]
