# Generated by Django 6.0.4 on 2026-04-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("results", "0003_exam_year_of_study_alter_exam_module"),
        ("students", "0003_remove_batch_department"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["batch__academic_start_year", "code"], "verbose_name": "Stream / Subject", "verbose_name_plural": "Streams / Subjects"},
        ),
        migrations.RemoveField(
            model_name="module",
            name="year_of_study",
        ),
        migrations.AlterField(
            model_name="module",
            name="semester",
            field=models.CharField(max_length=16),
        ),
    ]
