# Generated by Django 6.0.4 on 2026-04-15 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_module_options_remove_module_year_of_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='preferred_name',
        ),
    ]
