# Generated by Django 6.0.4 on 2026-04-14 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        ('results', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultupload',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='results.exam'),
        ),
        migrations.AddField(
            model_name='resultupload',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_result_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultuploadrow',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_result_rows', to='students.student'),
        ),
        migrations.AddField(
            model_name='resultuploadrow',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_rows_set', to='imports.resultupload'),
        ),
        migrations.AddConstraint(
            model_name='resultupload',
            constraint=models.UniqueConstraint(fields=('exam', 'checksum_sha256'), name='imports_upload_checksum_unique_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='resultupload',
            constraint=models.CheckConstraint(condition=models.Q(('staged_rows__gte', 0), ('imported_rows__gte', 0), ('rejected_rows__gte', 0)), name='imports_upload_non_negative_row_counts'),
        ),
        migrations.AddConstraint(
            model_name='resultuploadrow',
            constraint=models.UniqueConstraint(fields=('upload', 'row_number'), name='imports_upload_row_number_unique_per_upload'),
        ),
    ]
