# Generated by Django 6.0.4 on 2026-04-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultuploadrow',
            name='status',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('absent', 'Absent'), ('withheld', 'Withheld')], default='recorded', max_length=16),
        ),
    ]
