# Generated by Django 6.0.4 on 2026-04-14 23:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_resultuploadrow_status'),
        ('results', '0002_exam_release_state_exam_release_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultupload',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resultuploadrow',
            name='review_bucket',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddConstraint(
            model_name='resultupload',
            constraint=models.UniqueConstraint(fields=('exam', 'version_number'), name='imports_upload_version_unique_per_exam'),
        ),
    ]
