# Generated by Django 6.0.4 on 2026-04-15 01:30

import django.db.models.deletion
import imports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_resultupload_version_number_and_more'),
        ('students', '0004_alter_module_options_remove_module_year_of_study_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to=imports.models.student_upload_path)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('staged', 'Staged'), ('failed', 'Failed'), ('published', 'Published')], default='pending', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('staged_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('rejected_rows', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('staged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_student_uploads', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentUploadRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('registration_number', models.CharField(blank=True, max_length=32)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('preferred_name', models.CharField(blank=True, max_length=64)),
                ('university_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('leave', 'On leave'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], default='active', max_length=16)),
                ('batch_code', models.CharField(blank=True, max_length=32)),
                ('is_valid', models.BooleanField(default=False)),
                ('review_bucket', models.CharField(blank=True, max_length=16)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('duplicate_reason', models.CharField(blank=True, max_length=255)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_student_rows', to='students.batch')),
                ('created_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_student_upload_row', to='students.student')),
                ('matched_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_student_import_rows', to='students.student')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_rows_set', to='imports.studentupload')),
            ],
            options={
                'ordering': ['row_number'],
                'constraints': [models.UniqueConstraint(fields=('upload', 'row_number'), name='imports_student_upload_row_number_unique_per_upload')],
            },
        ),
    ]
