# Generated by Django 6.0.4 on 2026-04-15 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_studentupload_studentuploadrow'),
        ('students', '0005_remove_student_preferred_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuploadrow',
            name='batch_code',
        ),
        migrations.RemoveField(
            model_name='studentuploadrow',
            name='preferred_name',
        ),
        migrations.AddField(
            model_name='studentupload',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_uploads', to='students.batch'),
        ),
    ]
