# Generated by Django 6.0.4 on 2026-04-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_remove_studentuploadrow_batch_code_and_more'),
        ('results', '0007_alter_examresult_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultupload',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='results.exam'),
        ),
    ]
