# Generated by Django 6.0.4 on 2026-04-14 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('target_app', models.CharField(max_length=64)),
                ('target_model', models.CharField(max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(max_length=255)),
                ('sensitive', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['action', 'occurred_at'], name='audits_audi_action_aca387_idx'), models.Index(fields=['target_app', 'target_model', 'target_id'], name='audits_audi_target__f1112f_idx')],
            },
        ),
    ]
