# Generated by Django 6.0.4 on 2026-04-14 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        ('results', '0002_exam_release_state_exam_release_version_and_more'),
        ('students', '0002_alter_batch_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='channel',
            field=models.CharField(choices=[('web', 'Web'), ('admin', 'Admin'), ('service', 'Service'), ('management_command', 'Management command')], default='service', max_length=32),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='results.exam'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('forbidden', 'Forbidden'), ('failed', 'Failed')], default='success', max_length=16),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_method',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'occurred_at'], name='audits_audi_actor_i_519163_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['student', 'occurred_at'], name='audits_audi_student_3d70b5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['exam', 'occurred_at'], name='audits_audi_exam_id_13de8d_idx'),
        ),
    ]
