# Generated by Django 6.0.4 on 2026-04-15 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='checksum_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='last_verified_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='restore_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='retention_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['retention_expires_at'], name='backups_bac_retenti_95b2d8_idx'),
        ),
    ]
